- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    - { role: apt-cli, tags: [ apt-cli ] }
    - { role: oh-my-zsh, tags: [ oh-my-zsh ] }
    - { role: nodejs, tags: [ nodejs ] }
    - { role: color, tags: [ color ] }
    - { role: tig, tags: [ tig ] }
    - { role: tmux, tags: [ tmux ] }
    - { role: ghq, tags: [ ghq ] }
    - { role: git, tags: [ git ] }
    - { role: go, tags: [ go ] }
    - { role: python, tags: [ python ] }
    - { role: percol, tags: [ percol ] }
    - { role: rust, tags: [ rust ] }
    - { role: vim, tags: [ vim ] }
    - { role: node, tags: [ node ] }
    - { role: hashicorp, tags: [ hashicorp ] }
    - { role: gcp, tags: [ gcp ] }
    - { role: fff, tags: [ fff ] }

  vars_prompt:
    - name: "user_name"
      prompt: "Please enter your name (ex. Haruomi Hosono)"
      private: no

    - name: "user_email"
      prompt: "please enter your email address"
      private: no
