- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    - { role: fff, tags: [ fff ] }
    - { role: gnome, tags: [ gnome ] }
    - { role: apt-cli, tags: [ apt-cli ] }
    - { role: apt-gui, tags: [ apt-gui ] }
    - { role: color, tags: [ color ] }
    - { role: oh-my-zsh, tags: [ oh-my-zsh ] }
    - { role: tig, tags: [ tig ] }
    - { role: tmux, tags: [ tmux ] }
    - { role: ghq, tags: [ ghq ] }
    - { role: git, tags: [ git ] }
    - { role: peco, tags: [ peco ] }
    - { role: python, tags: [ python ] }
    - { role: slack, tags: [ slack ] }
    - { role: vscode, tags: [ vscode ] }
    - { role: usb, tags: [ usb ] }
    - { role: vim, tags: [ vim ] }
    - { role: xkeysnail, tags: [ xkeysnail ] }
    - { role: chrome, tags: [ chrome ] }

  vars_prompt:
    - name: "user_name"
      prompt: "Please enter your name (ex. Haruomi Hosono)"
      private: no

    - name: "user_email"
      prompt: "please enter your email address"
      private: no
