- name: check pyenv is installed?
  command: which pyenv
  ignore_errors: True
  register: pyenv_exist

- name: install pyenv
  shell: curl https://pyenv.run | bash
  when: pyenv_exist is failed

- name: check poetry is installed?
  command: which poetry
  ignore_errors: True
  register: poetry_exist

- name: install poetry
  shell: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
  when: poetry_exist is failed

- name: add poetry oh-my-zsh plugin folder
  file: path=~/.oh-my-zsh/custom/plugins/poetry state=directory mode=0755

- name: install poetry completions
  shell: poetry completions zsh > ~/.oh-my-zsh/custom/plugins/poetry/_poetry

- name: Installing pipx
  pip:
    name: pipx
    executable: pip3

- name: check ipython is installed?
  command: which ipython
  ignore_errors: True
  register: ipython_exist

- name: Install ipython
  shell: pipx install ipython
  when: ipython_exist is failed