- name: create a working directory
  file: path=~/temp/ state=directory mode=0755

- name: register a working directory full path
  command: find ~/temp -maxdepth 0
  register: workdir_result

- name: install dependency packages
  apt:
    pkg:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    update_cache: yes
  become: yes

- name: get docker official gpg key
  shell: >
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor --yes -o /usr/share/keyrings/docker-archive-keyring.gpg
  become: yes

- name: setup docker apt repository list
  shell: >
    echo
    "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  become: yes

- name: Install docker
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes
  become: yes

- name: create cli plugin directory
  file: path=~/.docker/cli-plugins state=directory mode=0755

- name: Get latest docker compose version
  shell: >
    curl -sI https://github.com/docker/compose/releases/latest | awk -F'/' '/^location:/{print $NF}'
  register: compose_latest_version

- name: register a cli plugin directory full path
  command: find ~/.docker/cli-plugins -maxdepth 0
  register: cli_plugin_dir

- name: Install latest docker compose v2
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ compose_latest_version.stdout }}/docker-compose-linux-x86_64"
    dest: "{{ cli_plugin_dir.stdout }}/docker-compose"
    mode: '755'
