- name: check xkeysnail is installed?
  command: which xkeysnail
  ignore_errors: True
  register: xkeysnail_exist

- name: Install xkeysnail
  shell: pipx install xkeysnail
  when: xkeysnail_exist is failed

- name: create ~/.xkeysnail/ directory
  file: path=~/.xkeysnail/ state=directory mode=0755

- name: copy xkeysnail setting
  template: src=config.py dest=~/.xkeysnail mode=0644

- name: add uinput group
  group:
    name: uinput
  become: yes

- name: Run whoami without become.
  command: whoami
  register: whoami

- name: add current user in uinput and input group
  user:
    name: "{{ whoami.stdout }}"
    groups: uinput,input
    append: yes
  become: yes

- name: add uinput rule in udev
  template: src=uinput.rules dest=/etc/udev/rules.d/
  become: yes

- name: add input rule in udev
  template: src=input.rules dest=/etc/udev/rules.d/
  become: yes

- name: reload udev rules
  shell: udevadm control --reload-rules && udevadm trigger
  become: yes

- name: create ~/.config/systemd/user/ directory
  file: path=~/.config/systemd/user/ state=directory mode=0755

- name: copy xkeysnail.services to ~/.config/systemd/user/xkeysnail.service
  template: src=xkeysnail.service.j2 dest=~/.config/systemd/user/xkeysnail.service mode=0644

- name: enable xkeysnail service
  command: systemctl --user enable xkeysnail

- name: start xkeysnail service
  command: systemctl --user start xkeysnail
