- name: create a working directory
  file: path=~/temp/ state=directory mode=0755

- name: register a working directory full path
  command: find ~/temp -maxdepth 0
  register: workdir_result

- name: install dependency packages
  apt:
    pkg:
    - ca-certificates
    - curl
    - gnupg
    update_cache: yes
  become: yes

- name: get hashicorp gpg key
  shell: >
    curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add
  become: yes

- name: setup hashicorp apt repository list
  shell: >
    echo
    "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  become: yes

- name: Install hashicorp tools
  apt:
    pkg:
      - terraform
    update_cache: yes
  become: yes