- name: create ~/src directory
  file: path=~/src/ state=directory

- name: create ~/bin directory
  file: path=~/bin state=directory

- name: Set ghq.root to $GOPATH/src
  git_config: name=ghq.root scope=global value=~/src

- name: set user.name
  git_config: name=user.name scope=global value="{{ user_name }}"

- name: set user.email
  git_config: name=user.email scope=global value="{{ user_email }}"

- name: set core.autocrlf
  git_config: name=core.autocrlf scope=global value=input

- name: set core.fscache
  git_config: name=core.fscache scope=global value=true

- name: set core.preloadindex
  git_config: name=core.preloadindex scope=global value=true

- name: set commit.verbose
  git_config: name=commit.verbose scope=global value=true

- name: set rebase.autostash
  git_config: name=rebase.autostash scope=global value=true

- name: set pull.rebase
  git_config: name=pull.rebase scope=global value=true

- name: set init.defaultBranch
  git_config: name=init.defaultBranch scope=global value=main

- name: download gibo
  get_url: url="https://raw.github.com/simonwhitaker/gibo/master/gibo" dest=~/bin/

- name: make gibo executable
  file: path=~/bin/gibo mode="0755"

- name: upgrade gibo
  command: ~/bin/gibo update

- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
  register: tmpdir

- name: download github cli gpg key
  get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: "{{ tmpdir.path }}/githubcli-archive-keyring.gpg"

- name: register github cli gpg key
  command: gpg --yes --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg {{ tmpdir.path}}/githubcli-archive-keyring.gpg
  become: yes

- name: add github cli apt source list
  copy: src=github-cli.list dest=/etc/apt/sources.list.d/github-cli.list
  become: yes

- name: apt-get update
  apt: update_cache=yes
  become: yes

- name: install github cli
  apt: name="gh"
  become: yes