- name: install tmux dependencies
  apt: name="{{ item.name }}" state="{{ item.state|default("latest") }}"
  with_items: "{{apt_packages}}"
  become: yes

- name: create a working directory
  file: path=~/temp/ state=directory mode=0755

- name: register a working directory full path
  command: find ~/temp -maxdepth 0
  register: workdir_result

- name: Get latest tmux version
  shell: >
    curl -sI https://github.com/tmux/tmux/releases/latest | awk -F'/' '/^location:/{print $NF}'
  register: tmux_latest_version

- name: Download latest tmux
  get_url: url=https://github.com/tmux/tmux/releases/download/{{ tmux_latest_version.stdout }}/tmux-{{ tmux_latest_version.stdout }}.tar.gz dest={{ workdir_result.stdout }}/tmux.tar.gz

- name: Extract tmux
  unarchive: src={{ workdir_result.stdout }}/tmux.tar.gz dest={{ workdir_result.stdout }} copy=no

- name: configure tmux
  command: ./configure
  args:
    chdir: "{{ workdir_result.stdout }}/tmux-{{ tmux_latest_version.stdout }}"

- name: make
  make: chdir={{ workdir_result.stdout }}/tmux-{{ tmux_latest_version.stdout }}

- name: make install
  make: chdir={{ workdir_result.stdout }}/tmux-{{ tmux_latest_version.stdout }} target=install
  become: yes

- name: Install tmux plugin manager
  git: repo=https://github.com/tmux-plugins/tpm dest=~/.tmux/plugins/tpm

- name: copy .tmux.conf
  template: src=.tmux.conf dest=~/.tmux.conf mode=0644

- name: copy scripts
  template: src="{{item.name}}" dest=~/tools/ mode=0755
  with_items: "{{scripts}}"